import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { createAttachmentFixture, destroyAttachmentFixture, bytes, storedFiles, upload, type AttachmentFixture } from "./attachment-test-fixture.js";

let f: AttachmentFixture;
beforeAll(async () => { f = await createAttachmentFixture("api11"); });
afterAll(async () => { await destroyAttachmentFixture(f); });

describe("API-11 Attachment upload", () => {
  it.each([
    ["photo.JPG", "image/jpeg", bytes.jpeg], ["image.png", "image/png", bytes.png],
    ["image.webp", "image/webp", bytes.webp], ["document.pdf", "application/pdf", bytes.pdf],
  ])("accepts %s and stores private generated bytes", async (filename, mime, data) => {
    const before = (await f.prisma.ticket.findUniqueOrThrow({ where: { id: f.ticketId } })).updatedAt;
    const response = await upload(f, f.requesterA.id, f.ticketId, data, filename, mime);
    expect(response.status).toBe(201);
    expect(response.body.attachment).toMatchObject({ ticketId: f.ticketId, originalName: filename, mimeType: mime, sizeBytes: data.length, state: "ACTIVE", removedAt: null, removalReason: null });
    expect(response.body.attachment).toHaveProperty("downloadUrl");
    expect(JSON.stringify(response.body)).not.toMatch(/storedName|filesystem|uploads|\\/i);
    const row = await f.prisma.attachment.findFirstOrThrow({ where: { ticketId: f.ticketId, originalName: filename } });
    expect(row.storedName).not.toContain(filename);
    expect(await storedFiles(f.root)).toContain(row.storedName);
    expect((await f.prisma.ticket.findUniqueOrThrow({ where: { id: f.ticketId } })).updatedAt.getTime()).toBeGreaterThan(before.getTime());
  });
});
