import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { createAttachmentFixture, destroyAttachmentFixture, bytes, upload, type AttachmentFixture } from "./attachment-test-fixture.js";
import request from "supertest";
let f: AttachmentFixture;
beforeAll(async () => { f = await createAttachmentFixture("api16"); }); afterAll(async () => { await destroyAttachmentFixture(f); });
describe("API-16 Attachment download", () => {
  it("returns exact bytes and safe headers without touching Ticket updatedAt", async () => { const a = await upload(f, f.requesterA.id, f.ticketId, bytes.png, "download.png", "image/png"); const before = (await f.prisma.ticket.findUniqueOrThrow({ where: { id: f.ticketId } })).updatedAt; const r = await request(f.app).get(`/api/tickets/${f.ticketId}/attachments/${a.body.attachment.id}/download`).set("X-Development-Requester-Id", String(f.requesterA.id)); expect(r.status).toBe(200); expect(Buffer.from(r.body)).toEqual(bytes.png); expect(r.headers["content-type"]).toContain("image/png"); expect(r.headers["content-disposition"]).toMatch(/attachment/); expect(r.headers["x-content-type-options"]).toBe("nosniff"); expect(r.headers["cache-control"]).toMatch(/private|no-store/); expect((await f.prisma.ticket.findUniqueOrThrow({ where: { id: f.ticketId } })).updatedAt.getTime()).toBe(before.getTime()); });
  it("uses the same 404 for missing, removed, mismatched, and cross-owner resources", async () => { const a = await upload(f, f.requesterA.id, f.ticketId, bytes.pdf, "gone.pdf", "application/pdf"); await f.prisma.attachment.update({ where: { id: a.body.attachment.id }, data: { removedAt: new Date(), removalReason: "gone" } }); for (const [ticketId, attachmentId, requesterId] of [[f.ticketId, a.body.attachment.id, f.requesterA.id], [f.ticketId, 999999, f.requesterA.id], [f.foreignTicketId, a.body.attachment.id, f.requesterA.id], [f.ticketId, a.body.attachment.id, f.requesterB.id]]) { const r = await request(f.app).get(`/api/tickets/${ticketId}/attachments/${attachmentId}/download`).set("X-Development-Requester-Id", String(requesterId)); expect(r.status).toBe(404); expect(r.body).toEqual({ error: { code: "RESOURCE_NOT_FOUND", message: "Attachment not found" } }); } });
  it("returns safe 500 when active metadata points to missing bytes", async () => { const a = await upload(f, f.requesterA.id, f.ticketId, bytes.jpeg, "missing.jpg", "image/jpeg"); const row = await f.prisma.attachment.findUniqueOrThrow({ where: { id: a.body.attachment.id } }); await import("node:fs/promises").then(({ rm }) => rm(`${f.root}/${row.storedName}`, { force: true })); const r = await request(f.app).get(`/api/tickets/${f.ticketId}/attachments/${row.id}/download`).set("X-Development-Requester-Id", String(f.requesterA.id)); expect(r.status).toBe(500); expect(r.body).toEqual({ error: { code: "INTERNAL_ERROR", message: "Attachment is temporarily unavailable" } }); });
});
