import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { createAttachmentFixture, destroyAttachmentFixture, bytes, upload, type AttachmentFixture } from "./attachment-test-fixture.js";
import request from "supertest";
let f: AttachmentFixture;
beforeAll(async () => { f = await createAttachmentFixture("api17"); }); afterAll(async () => { await destroyAttachmentFixture(f); });
describe("API-17 Attachment soft removal", () => {
  it("trims a valid reason, advances Ticket, denies later download, and keeps repeated removal non-disclosing", async () => { const a = await upload(f, f.requesterA.id, f.ticketId, bytes.png, "remove.png", "image/png"); const before = (await f.prisma.ticket.findUniqueOrThrow({ where: { id: f.ticketId } })).updatedAt; const r = await request(f.app).delete(`/api/tickets/${f.ticketId}/attachments/${a.body.attachment.id}`).set("X-Development-Requester-Id", String(f.requesterA.id)).send({ removalReason: "  obsolete file  " }); expect(r.status).toBe(200); expect(r.body.attachment).toMatchObject({ state: "REMOVED", removalReason: "obsolete file", downloadUrl: null }); const row = await f.prisma.attachment.findUniqueOrThrow({ where: { id: a.body.attachment.id } }); expect(row.removedAt).not.toBeNull(); expect((await f.prisma.ticket.findUniqueOrThrow({ where: { id: f.ticketId } })).updatedAt.getTime()).toBeGreaterThan(before.getTime()); const again = await request(f.app).delete(`/api/tickets/${f.ticketId}/attachments/${a.body.attachment.id}`).set("X-Development-Requester-Id", String(f.requesterA.id)).send({ removalReason: "changed" }); expect(again.status).toBe(404); expect((await f.prisma.attachment.findUniqueOrThrow({ where: { id: a.body.attachment.id } })).removalReason).toBe("obsolete file"); });
  it.each(["", "ab", "x".repeat(201), "   "]) ("rejects invalid reason %s", async (reason) => { const a = await upload(f, f.requesterA.id, f.ticketId, bytes.pdf, `${Math.random()}.pdf`, "application/pdf"); const r = await request(f.app).delete(`/api/tickets/${f.ticketId}/attachments/${a.body.attachment.id}`).set("X-Development-Requester-Id", String(f.requesterA.id)).send({ removalReason: reason }); expect(r.status).toBe(400); expect(r.body.error.code).toBe("VALIDATION_ERROR"); expect((await f.prisma.attachment.findUniqueOrThrow({ where: { id: a.body.attachment.id } })).removedAt).toBeNull(); });
});
