import { afterAll, beforeAll, describe, expect, it, vi } from "vitest";
import { createAttachmentFixture, destroyAttachmentFixture, bytes, downloadAsRequester, listAsRequester, removeAsRequester, storageEntries, upload, type AttachmentFixture } from "./attachment-test-fixture.js";
let f: AttachmentFixture;
beforeAll(async () => { f = await createAttachmentFixture("api18"); }); afterAll(async () => { await destroyAttachmentFixture(f); });
describe("API-18 ownership and failure compensation", () => {
  it("denies foreign metadata, upload, download, and removal", async () => { const a = await upload(f, f.requesterB.id, f.foreignTicketId, bytes.png, "foreign.png", "image/png"); for (const r of [await listAsRequester(f, f.requesterA.id, f.foreignTicketId), await upload(f, f.requesterA.id, f.foreignTicketId, bytes.png, "nope.png", "image/png"), await downloadAsRequester(f, f.requesterA.id, f.foreignTicketId, a.body.attachment.id), await removeAsRequester(f, f.requesterA.id, f.foreignTicketId, a.body.attachment.id, "nope")]) { expect(r.status).toBe(404); expect(JSON.stringify(r.body)).not.toMatch(/foreign|storedName|uploads/i); } expect((await f.prisma.attachment.findUniqueOrThrow({ where: { id: a.body.attachment.id } })).removedAt).toBeNull(); });
  it("maps controlled storage failure to safe 500 and cleans final/staging entries", async () => { const before = await storageEntries(f.root); const { attachmentStorage } = await import("../../src/attachment-storage.js"); const spy = vi.spyOn(attachmentStorage, "finalize").mockRejectedValueOnce(new Error("C:\\private\\secret path")); const r = await upload(f, f.requesterA.id, f.ticketId, bytes.pdf, "failure.pdf", "application/pdf"); expect(r.status).toBe(500); expect(r.body).toEqual({ error: { code: "INTERNAL_ERROR", message: "Unable to upload attachment" } }); expect(JSON.stringify(r.body)).not.toMatch(/private|secret|path|Prisma/i); expect(await f.prisma.attachment.findFirst({ where: { originalName: "failure.pdf" } })).toBeNull(); expect(await storageEntries(f.root)).toEqual(before); spy.mockRestore(); });
  it("compensates when the database transaction fails after final storage", async () => { const before = await storageEntries(f.root); const { getPrisma } = await import("../../src/prisma.js"); const routePrisma = getPrisma(); const spy = vi.spyOn(routePrisma, "$transaction").mockRejectedValueOnce(new Error("Prisma SQL password secret")); const r = await upload(f, f.requesterA.id, f.ticketId, bytes.png, "db-failure.png", "image/png"); expect(r.status).toBe(500); expect(r.body).toEqual({ error: { code: "INTERNAL_ERROR", message: "Unable to upload attachment" } }); expect(await f.prisma.attachment.findFirst({ where: { originalName: "db-failure.png" } })).toBeNull(); expect(await storageEntries(f.root)).toEqual(before); spy.mockRestore(); });
});
