import { afterAll, beforeAll, describe, expect, it, vi } from "vitest";
import { createAttachmentFixture, destroyAttachmentFixture, bytes, upload, type AttachmentFixture } from "./attachment-test-fixture.js";
import request from "supertest";
let f: AttachmentFixture;
beforeAll(async () => { f = await createAttachmentFixture("api18"); }); afterAll(async () => { await destroyAttachmentFixture(f); });
describe("API-18 ownership and failure compensation", () => {
  it("denies foreign metadata, upload, download, and removal", async () => { const a = await upload(f, f.requesterB.id, f.foreignTicketId, bytes.png, "foreign.png", "image/png"); for (const r of [await request(f.app).get(`/api/tickets/${f.foreignTicketId}/attachments`).set("X-Development-Requester-Id", String(f.requesterA.id)), await upload(f, f.requesterA.id, f.foreignTicketId, bytes.png, "nope.png", "image/png"), await request(f.app).get(`/api/tickets/${f.foreignTicketId}/attachments/${a.body.attachment.id}/download`).set("X-Development-Requester-Id", String(f.requesterA.id)), await request(f.app).delete(`/api/tickets/${f.foreignTicketId}/attachments/${a.body.attachment.id}`).set("X-Development-Requester-Id", String(f.requesterA.id)).send({ removalReason: "nope" })]) { expect(r.status).toBe(404); expect(JSON.stringify(r.body)).not.toMatch(/foreign|storedName|uploads/i); } expect((await f.prisma.attachment.findUniqueOrThrow({ where: { id: a.body.attachment.id } })).removedAt).toBeNull(); });
  it("maps controlled storage failure to safe 500 with no metadata", async () => { const { attachmentStorage } = await import("../../src/attachment-storage.js"); const spy = vi.spyOn(attachmentStorage, "finalize").mockRejectedValueOnce(new Error("C:\\private\\secret path")); const r = await upload(f, f.requesterA.id, f.ticketId, bytes.pdf, "failure.pdf", "application/pdf"); expect(r.status).toBe(500); expect(r.body).toEqual({ error: { code: "INTERNAL_ERROR", message: "Unable to upload attachment" } }); expect(JSON.stringify(r.body)).not.toMatch(/private|secret|path|Prisma/i); expect(await f.prisma.attachment.findFirst({ where: { originalName: "failure.pdf" } })).toBeNull(); spy.mockRestore(); });
  it("compensates when the database transaction fails after final storage", async () => { const { getPrisma } = await import("../../src/prisma.js"); const routePrisma = getPrisma(); const spy = vi.spyOn(routePrisma, "$transaction").mockRejectedValueOnce(new Error("Prisma SQL password secret")); const r = await upload(f, f.requesterA.id, f.ticketId, bytes.png, "db-failure.png", "image/png"); expect(r.status).toBe(500); expect(r.body).toEqual({ error: { code: "INTERNAL_ERROR", message: "Unable to upload attachment" } }); expect(await f.prisma.attachment.findFirst({ where: { originalName: "db-failure.png" } })).toBeNull(); spy.mockRestore(); });
});
